# opencode-watch 配置文件
# 智能tmux pane监控和自动干预工具配置

## tmux 配置
tmux:
  pane: "%18"              # 监控的tmux pane ID (例如: %18, %17, main)

## 监控配置
monitoring:
  interval: 5               # 监控间隔（秒）- 建议5-15秒
  stuck_sec: 15             # 卡住判定时间（秒）- 建议20-60秒
  max_retry: 1000             # 最大重试次数 - 建议6次以支持完整命令循环

## 干预配置
intervention:
  # 指令发送延迟配置（毫秒）
  command_delay_ms: 1000    # 指令输入完成后等待时间
  enter_delay_ms: 3000      # 回车键发送延迟时间
  
  # 干预指令列表 - 按顺序循环使用
  # 每次检测到卡住时，会按顺序选择下一条指令执行
  commands:
    - "继续"                 # 基础继续指令
    - "Continue"
    - "请继续"               # 礼貌请求
    - "continue"
    - "请继续"               # 礼貌请求
    - "继续"                 # 基础继续指令
    - "继续工作，如果你忘了要干什么，就去看一眼之前写的工作记录"              # 友好提示
    - "请继续"               # 礼貌请求
    - "继续工作，记得定期做git commit"             # 上下文压缩指令（特殊处理）
    - "请继续工作，并记得编写工作记录"            # 礼貌的工作继续请求

