tmux:
  pane: "%19"

llm:
  backend: "none"

monitoring:
  interval: 8
  stuck_sec: 30
  max_retry: 5
  intervention_commands:
    - "继续"
    - "继续工作"
    - "请继续"
    - "/compact"
    - "重新开始"
    - "恢复工作"